apiVersion: manifests.package-operator.run/v1alpha1
kind: PackageManifest
metadata:
  name: metrics-forwarder
spec:
  scopes:
    - Namespaced
  phases:
    - name: certman-issuer
    - name: certman-cert
    - name: config
    - name: deploy
    - name: expose
  availabilityProbes:
    - selector:
        kind:
          groups: cert-manager.io
          kind: Issuer
      probes:
      - condition:
          type: Ready
          status: "True"
test:
  template:
  - name: default
    context:
      environment:
        hyperShift:
          hostedCluster:
            hostedClusterNamespace: ocm-staging-24o19ba52km496nvegb629918l9gbnvu-bmeng-hcp
            metadata:
              name: bmeng
              annotations: {}
  - name: dedicated-request-serving-nodes
    context:
      environment:
        hyperShift:
          hostedCluster:
            hostedClusterNamespace: ocm-staging-24o19ba52km496nvegb629918l9gbnvu-bmeng-hcp
            metadata:
              name: bmeng
              annotations:
                hypershift.openshift.io/request-serving-node-additional-selector: selector-label=beeeeeg-node

