apiVersion: manifests.package-operator.run/v1alpha1
kind: PackageManifest
metadata:
  name: metrics-forwarder
spec:
  scopes:
    - Namespaced
  phases:
    - name: certman-issuer
    - name: certman-cert
    - name: config
    - name: deploy
    - name: expose
  availabilityProbes:
    - selector:
        kind:
          groups: cert-manager.io
          kind: Issuer
      probes:
      - condition:
          type: Ready
          status: "True"
test:
  template:
  # default HyperShift HCP template test.
  - name: default
    context:
      package:
        metadata:
          name: metrics-forwarder
          namespace: ocm-staging-24o19ba52km496nvegb629918l9gbnvu-bmeng-hcp
